<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tenant_id')->constrained()->cascadeOnDelete();
            $table->foreignId('category_id')->nullable()->constrained()->nullOnDelete();

            // Generated by the configurable ID mechanism (see tenants.sku_*).
            $table->string('sku', 64);
            $table->string('name', 191);
            $table->text('description')->nullable();
            $table->string('unit', 20)->default('pcs');

            $table->decimal('cost_price', 15, 2)->default(0);
            $table->decimal('price', 15, 2)->default(0);
            $table->decimal('wholesale_price', 15, 2)->nullable();
            $table->unsignedInteger('min_wholesale_qty')->default(0);
            $table->boolean('tax_exempt')->default(false);

            $table->boolean('track_stock')->default(true);
            $table->decimal('stock', 15, 3)->default(0);
            $table->decimal('min_stock', 15, 3)->default(0);

            // Scannable identifiers, both derived automatically on create.
            $table->string('barcode_value', 64)->nullable();
            $table->enum('barcode_type', ['C128', 'EAN13'])->default('C128');
            $table->string('qr_value', 191)->nullable();

            $table->string('image_path', 191)->nullable();
            $table->boolean('is_active')->default(true);
            $table->boolean('is_favorite')->default(false);
            $table->unsignedInteger('sold_count')->default(0);

            $table->timestamps();
            $table->softDeletes();

            $table->unique(['tenant_id', 'sku']);
            $table->unique(['tenant_id', 'barcode_value']);
            $table->index(['tenant_id', 'is_active']);
            $table->index(['tenant_id', 'category_id']);
            $table->index('name');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};
